/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-08 07:46:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/content/tool/countLetters.jsp", Long.valueOf(1654154910805L));
    _jspx_dependants.put("/content/registration/register.jsp", Long.valueOf(1653042645744L));
    _jspx_dependants.put("/footer/footer.jsp", Long.valueOf(1652597101152L));
    _jspx_dependants.put("/content/apply/recruitSites.jsp", Long.valueOf(1653296488268L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-8.5.78/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("file:/C:/apache-tomcat-8.5.78/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1648717528000L));
    _jspx_dependants.put("/content/registration/login.jsp", Long.valueOf(1653039689613L));
    _jspx_dependants.put("/content/apply/monthlyApply.jsp", Long.valueOf(1653294044782L));
    _jspx_dependants.put("/header/header.jsp", Long.valueOf(1653039566034L));
    _jspx_dependants.put("/menu/main_menu.jsp", Long.valueOf(1653906285400L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>취업하고 싶어서</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/main.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/main_menu.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/apply/currentApply.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/apply/monthlyApply.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/apply/recruitSites.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/tool/commonTool.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/login.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"css/register.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/header.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id = \"main_box\">\r\n");
      out.write("      <div id = \"header\">\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class = \"headbox\">\r\n");
      out.write("      <a id = \"hamberger\" onclick = \"showMenu()\" href = \"#\"><img alt=\"메뉴\" src=\"image/menu.png\"></a>\r\n");
      out.write("      <h1 id = \"logo\"><a href = \"?menu=home\">취업하고 싶어서</a></h1>\r\n");
      out.write("      <div class = \"headbuttons\">\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='?menu=login';\">로그인</button>\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='?menu=register';\">회원가입</button>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("       <div id = \"menu\">\r\n");
      out.write("	         ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JSTL Library 연결 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- Main Menu -->\r\n");
      out.write("   <ul id = \"main_menu\">\r\n");
      out.write("     <li>\r\n");
      out.write("        <h3 class = \"menu_title\">채용 사이트</h3>\r\n");
      out.write("	    <ul class = \"menu_large\">\r\n");
      out.write("	      <li><a href = \"?menu=recruitSites\">채용정보 확인/지원</a></li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("     </li>\r\n");
      out.write("     <li>\r\n");
      out.write("        <h3 class = \"menu_title\">마이 지원함</h3>\r\n");
      out.write("	    <ul class = \"menu_large\">\r\n");
      out.write("	      <li><a href = \"?menu=currentApply\">지원 분석</a></li>\r\n");
      out.write("	      <li><a href = \"?menu=monthlyApply\">월간 일정</a></li>\r\n");
      out.write("	      <li><a href = \"?menu=applications\">이력서 모음</a></li>\r\n");
      out.write("	   </ul>\r\n");
      out.write("     </li>\r\n");
      out.write("     <li>\r\n");
      out.write("       <h3 class = \"menu_title\">유용한 툴</h3>\r\n");
      out.write("	   <ul class = \"menu_large\">\r\n");
      out.write("	      <li><a href = \"?menu=countLetters\">글자수 세기</a></li>\r\n");
      out.write("	      <li><a href = \"#\">연봉 계산기</a></li>\r\n");
      out.write("	   </ul>\r\n");
      out.write("     </li>\r\n");
      out.write("     <li>\r\n");
      out.write("       <h3 class = \"menu_title\">게시판</h3>\r\n");
      out.write("	   <ul class = \"menu_large\">\r\n");
      out.write("	      <li><a href = \"#\">정보 게시판</a></li>\r\n");
      out.write("	      <li><a href = \"#\">자유 게시판</a></li>\r\n");
      out.write("	   </ul>\r\n");
      out.write("     </li>\r\n");
      out.write("     <li>\r\n");
      out.write("       <h3 class = \"menu_title\">고객센터</h3>\r\n");
      out.write("	   <ul class = \"menu_large\">\r\n");
      out.write("	      <li><a href = \"?menu=memberInfo\">회원정보 수정</a></li>\r\n");
      out.write("	   </ul>\r\n");
      out.write("     </li>\r\n");
      out.write("   </ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	   </div>\r\n");
      out.write("   	  </div>\r\n");
      out.write("	   <div id = \"content_box\">\r\n");
      out.write("	      <div id = \"content\">\r\n");
      out.write("	         <!-- 메인(홈) 콘텐츠/ 채용사이트 > 채용정보 확인/지원 -->\r\n");
      out.write("	         ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	         \r\n");
      out.write("	         <!-- 회원 > 로그인 -->\r\n");
      out.write("	         ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	         <!-- 회원 > 회원가입 -->\r\n");
      out.write("	         ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	         \r\n");
      out.write("	         <!-- 마이지원함 > 전체 목록 -->\r\n");
      out.write("	         <!-- 마이지원함 > 월간 일정 -->\r\n");
      out.write("	         ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	         <!-- 마이지원함 > 이력서 모음 -->\r\n");
      out.write("	         \r\n");
      out.write("	         <!-- 유용한툴 > 글자수 세기 -->\r\n");
      out.write("	         ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	      </div>\r\n");
      out.write("      </div> <!-- end content_box -->\r\n");
      out.write("      <div id = \"footer\">\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(\"document\").ready(function(){\r\n");
      out.write("	   $(\"#footer_content > div > p\").css(\"display\",\"inline-block\").css(\"margin-right\",\"15px\");\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id = \"footer_content\">\r\n");
      out.write("      <div>\r\n");
      out.write("         <p>심플인 고객센터 02-0000-0000 (평일 09:00~19:00, 주말공휴일 휴무)</p>\r\n");
      out.write("         <p>이메일 : goeun930705@gmail.com</p>\r\n");
      out.write("         <p>FAX  : 02-0000-0000</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("         <p><a href = \"why-dev.tistory.com\" target = \"blank\">심플한개발 티스토리</a></p>\r\n");
      out.write("         <p><a href = \"why-dev.tistory.com\" target = \"blank\">심플한개발 티스토리</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /main.jsp(35,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ (empty param.menu) or (param.menu == 'home') or (param.menu == 'recruitSites') }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta charset=\"UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write("<script src = \"js/content/recruitSites.js\"></script>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("   <!-- 네비게이션 버튼 -->\r\n");
          out.write("   <div class=\"navi_menu btn-group\">\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this);\">사람인</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">잡코리아</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">원티드</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">워크넷</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">커리어</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">스카우트</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">인디드</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">벼룩시장</button>\r\n");
          out.write("	  <button type=\"button\" class=\"btn btn-primary\" onclick = \"siteOpen(this)\">피플앤잡</button>\r\n");
          out.write("	  <div class=\"btn-group\">\r\n");
          out.write("	    <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
          out.write("	    공공기관 <span class=\"caret\"></span></button>\r\n");
          out.write("	    <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("	      <li><a href=\"https://www.alio.go.kr\" target = \"blank\">알리오</a></li>\r\n");
          out.write("	      <li><a href=\"https://www.gojobs.go.kr\" target = \"blank\">나라일터</a></li>\r\n");
          out.write("	    </ul>\r\n");
          out.write("	  </div>\r\n");
          out.write("	  <div class=\"btn-group\">\r\n");
          out.write("	    <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
          out.write("	    평점확인 <span class=\"caret\"></span></button>\r\n");
          out.write("	    <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("	      <li><a href=\"https://www.jobplanet.co.kr\" target = \"blank\">잡플래닛</a></li>\r\n");
          out.write("	      <li><a href=\"https://www.kreditjob.com\" target = \"blank\">크레딧잡</a></li>\r\n");
          out.write("	      <li><a href=\"https://www.teamblind.com\" target = \"blank\">블라인드</a></li>\r\n");
          out.write("	    </ul>\r\n");
          out.write("	  </div>\r\n");
          out.write("   </div>\r\n");
          out.write("   \r\n");
          out.write("   <!-- 지원 등록 폼 -->\r\n");
          out.write("   <div id = \"insertRecruitBox\">\r\n");
          out.write("      <form action=\"\" method = \"post\">\r\n");
          out.write("	      <table id = \"insertRecruitTable\" class=\"w3-table w3-bordered\">\r\n");
          out.write("	          <tr>\r\n");
          out.write("	            <th>채용사이트</th>\r\n");
          out.write("	            <td>\r\n");
          out.write("	              <input type = \"text\">\r\n");
          out.write("	            </td>\r\n");
          out.write("	            <th class = \"leftLine\">URL</th>\r\n");
          out.write("	            <td><input type = \"text\"></td>\r\n");
          out.write("	          </tr>\r\n");
          out.write("	          <tr>\r\n");
          out.write("	            <th>기업명</th>\r\n");
          out.write("	            <td>\r\n");
          out.write("	              <input type = \"text\">\r\n");
          out.write("	            </td>\r\n");
          out.write("	            <th class = \"leftLine\">포지션명</th>\r\n");
          out.write("	            <td>\r\n");
          out.write("	              <input type = \"text\">\r\n");
          out.write("	            </td>\r\n");
          out.write("	          </tr>\r\n");
          out.write("	          <tr>\r\n");
          out.write("	            <th>나의 지원</th>\r\n");
          out.write("	            <td colspan = \"3\">\r\n");
          out.write("	              <div class=\"w3-container\">\r\n");
          out.write("	                  <!-- 현재 단계 선택 -->\r\n");
          out.write("					  <label>단계</label>\r\n");
          out.write("					  <div class=\"w3-dropdown-hover\">\r\n");
          out.write("					    <button class=\"w3-button w3-black\">어느 단계인가요?</button>\r\n");
          out.write("					    <div class=\"w3-dropdown-content w3-bar-block w3-border\">\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">서류</a>\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">코딩테스트</a>\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">면접</a>\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">발표</a>\r\n");
          out.write("					    </div>\r\n");
          out.write("					  </div>\r\n");
          out.write("					  <!-- 현재 상태 선택 -->\r\n");
          out.write("					  <label>상태</label>\r\n");
          out.write("					  <div class=\"w3-dropdown-hover\">\r\n");
          out.write("					    <button class=\"w3-button w3-black\">어떤 상태인가요?</button>\r\n");
          out.write("					    <div class=\"w3-dropdown-content w3-bar-block w3-border\">\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">진행중</a>\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">완료</a>\r\n");
          out.write("					      <a class=\"w3-bar-item w3-button\">종료</a>\r\n");
          out.write("					    </div>\r\n");
          out.write("					  </div>\r\n");
          out.write("				  </div>\r\n");
          out.write("	            </td>\r\n");
          out.write("	          </tr>\r\n");
          out.write("	          <tr>\r\n");
          out.write("	            <th>상세 일정</th>\r\n");
          out.write("	            <td colspan = \"3\">\r\n");
          out.write("	              <ul id = \"dates\">\r\n");
          out.write("	                <li class = \"dates_list\">\r\n");
          out.write("	                  <label>서류마감일</label>\r\n");
          out.write("	                  <input type = \"date\" id = \"paperDday\">\r\n");
          out.write("	                  <label class = \"recruitDesc\">예정 일정이 없으면 일정 없이 제출해주세요(이하동문).</label>\r\n");
          out.write("	                </li>\r\n");
          out.write("	                <li class = \"dates_list\">\r\n");
          out.write("	                  <label>코테예정일</label>\r\n");
          out.write("	                  <input type = \"date\" id = \"cotestDday\">\r\n");
          out.write("	                </li>\r\n");
          out.write("	                <li class = \"dates_list\">\r\n");
          out.write("	                  <label>면접예정일</label>\r\n");
          out.write("	                  <input type = \"date\" id = \"interviewDday\">\r\n");
          out.write("	                </li>\r\n");
          out.write("	                <li class = \"dates_list\">\r\n");
          out.write("	                  <label>발표예정일</label>\r\n");
          out.write("	                  <input type = \"date\" id = \"AnnounceDday\">\r\n");
          out.write("	                </li>\r\n");
          out.write("	              </ul>\r\n");
          out.write("	            </td>\r\n");
          out.write("	          </tr>\r\n");
          out.write("	      </table>\r\n");
          out.write("	      <div class = \"recruitButtons\">\r\n");
          out.write("	         <button type = \"submit\" class = \"btn btn-primary\">등록</button>\r\n");
          out.write("			         <button type = \"reset\" class = \"btn btn-warning\">취소</button>\r\n");
          out.write("			         <button class = \"btn btn-danger\">삭제</button>\r\n");
          out.write("			      </div>\r\n");
          out.write("		      </form>\r\n");
          out.write("		   </div>\r\n");
          out.write("		   \r\n");
          out.write("		   <!-- 지원 사이트 뷰어 -->\r\n");
          out.write("		   <div class = \"recView_box\" id = \"recSiteBox\">\r\n");
          out.write("		   	  <div style = \"height:900px; background : yellow\">임시 영역</div>\r\n");
          out.write("		   </div>\r\n");
          out.write("		   \r\n");
          out.write("		   <!-- 지원 목록 리스트 -->\r\n");
          out.write("		   <div class = \"recView_box\" id = \"recListBox\">\r\n");
          out.write("		      <div style = \"height:900px; background : blue\">임시 영역</div>\r\n");
          out.write("		   </div>\r\n");
          out.write("		</body>\r\n");
          out.write("		</html>");
          out.write("\r\n");
          out.write("	         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /main.jsp(40,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.menu == 'login' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta charset=\"UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write("<script src=\"js/login.js\"></script>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("   <div id = \"login_box\" class = \"container\">\r\n");
          out.write("      <form>\r\n");
          out.write("         <table>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <th><h2 id = \"login_title\">취업하고 싶어서</h2></th>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <input placeholder = \"아이디\" type = \"text\" name = \"userId\" id = \"userId\">\r\n");
          out.write("                <p class = \"input_validation id_valid\">아이디를 입력하세요.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <input placeholder = \"비밀번호\" type = \"text\" name = \"userPwd\" id = \"userPwd\">\r\n");
          out.write("                <p class = \"input_validation pwd_valid\">비밀번호를 입력하세요.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <input type = \"checkbox\" id = \"login_status\" name = \"login_status\">\r\n");
          out.write("                <label>로그인 상태 유지</label>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <button type = \"button\" id = \"btn_login\" class=\"btn btn-info\" onclick = \"return loginSend(this.form)\">로그인</button>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <button type = \"button\" class = \"btn_bottom btn_findPassword btn-default\">비밀번호 찾기</button>\r\n");
          out.write("                <button type = \"button\" class = \"btn_bottom btn_findID btn-default\">아이디 찾기</button>\r\n");
          out.write("                <button type = \"button\" class = \"btn_bottom btn_reg btn-default\" onclick=\"location.href='?menu=register'\">회원가입</button>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("         </table>\r\n");
          out.write("      </form>\r\n");
          out.write("   </div>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write("\r\n");
          out.write("	         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /main.jsp(44,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.menu == 'register' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta charset=\"UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write("<script src=\"js/register.js\"></script>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("	<div id = \"register_box\" class = \"container\">\r\n");
          out.write("	   <form>\r\n");
          out.write("	      <table>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <th><h2 id = \"register_title\">취업하고 싶어서</h2></th>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <label>아이디</label>\r\n");
          out.write("                <input type = \"text\" name = \"rgUserId\" id = \"rgUserId\">\r\n");
          out.write("                <p class = \"input_validation rgId_valid\">필수 정보입니다.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <label>비밀번호</label>\r\n");
          out.write("                <input type = \"text\" name = \"rgUserPwd\" id = \"rgUserPwd\">\r\n");
          out.write("                <p class = \"input_validation rePwd_valid\">필수 정보입니다.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <label>비밀번호 재확인</label>\r\n");
          out.write("                <input type = \"text\" name = \"rgUserRePwd\" id = \"rgUserRePwd\">\r\n");
          out.write("                <p class = \"input_validation reRePwd_valid\">필수 정보입니다.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <label>닉네임</label>\r\n");
          out.write("                <input type = \"text\" name = \"rgUserNickName\" id = \"rgUserNickName\">\r\n");
          out.write("                <p class = \"input_validation rgNickName_valid\">필수 정보입니다.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <label>휴대전화</label>\r\n");
          out.write("                <input type = \"text\" name = \"rgUserPhone\" id = \"rgUserPhone\">\r\n");
          out.write("                <button type = \"button\" id = \"btn_rgphoneValid\" class=\"btn btn-info\">인증번호 받기</button>\r\n");
          out.write("                <input type = \"text\" placeholder = \"인증번호 입력하세요\" name = \"rgCertifyPhone\" id = \"rgCertifyPhone\" readonly>\r\n");
          out.write("                <p class = \"input_validation rgPhone_valid\">필수 정보입니다.</p>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>\r\n");
          out.write("                <button type = \"button\" id = \"btn_register\" class=\"btn btn-info\" onclick = \"return regSend(this.form)\">회원가입</button>\r\n");
          out.write("              </td>\r\n");
          out.write("            </tr>\r\n");
          out.write("         </table>\r\n");
          out.write("	   </form>\r\n");
          out.write("	</div>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write("\r\n");
          out.write("	         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /main.jsp(50,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.menu == 'monthlyApply' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta charset=\"UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("   <form method = \"post\" action=\"\">\r\n");
          out.write("      <div id = \"calendar_title\">\r\n");
          out.write("         <button class = \"button\">&lt;&lt;</button>\r\n");
          out.write("         <button class = \"button\">&lt;</button>\r\n");
          out.write("      	 <h3><em>2022</em>년&nbsp;<em>08</em>월 일정</h3>\r\n");
          out.write("      	 <button class = \"button\">&gt;</button>\r\n");
          out.write("      	 <button class = \"button\">&gt;&gt;</button>\r\n");
          out.write("      </div>\r\n");
          out.write("      <table id = \"monthTable\">\r\n");
          out.write("          <tr>\r\n");
          out.write("            <th>일</th>\r\n");
          out.write("            <th>월</th>\r\n");
          out.write("            <th>화</th>\r\n");
          out.write("            <th>수</th>\r\n");
          out.write("            <th>목</th>\r\n");
          out.write("            <th>금</th>\r\n");
          out.write("            <th>토</th>\r\n");
          out.write("          </tr>\r\n");
          out.write("          <tr>\r\n");
          out.write("            <td class = \"sunday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"monday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"tuesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"wednesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"thursday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"friday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"saturday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("          </tr>\r\n");
          out.write("          <tr>\r\n");
          out.write("            <td class = \"sunday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"monday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"tuesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"wednesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"thursday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"friday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"saturday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("          </tr>\r\n");
          out.write("          <tr>\r\n");
          out.write("            <td class = \"sunday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"monday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"tuesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"wednesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"thursday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"friday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"saturday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("          </tr>\r\n");
          out.write("          <tr>\r\n");
          out.write("            <td class = \"sunday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"monday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"tuesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"wednesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"thursday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"friday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"saturday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("          </tr>\r\n");
          out.write("          <tr>\r\n");
          out.write("            <td class = \"sunday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"monday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"tuesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"wednesday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"thursday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"friday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("            <td class = \"saturday\">\r\n");
          out.write("              <div id = \"dateInfo\">\r\n");
          out.write("                 <em class = \"date\">31</em>\r\n");
          out.write("                 <ul class = \"schedule_list\">\r\n");
          out.write("                   <li><a href=\"#\">[서류]어느곳</a></li>\r\n");
          out.write("                 </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("            </td>\r\n");
          out.write("          </tr>\r\n");
          out.write("      </table>\r\n");
          out.write("   </form>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write("\r\n");
          out.write("	         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /main.jsp(56,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.menu == 'countLetters' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta charset=\"UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write("<script type=\"text/javascript\">\r\n");
          out.write("	/* textarea의 글자수를 세어주는 제이쿼리문 */\r\n");
          out.write("	$(document).ready(function() {\r\n");
          out.write("	    $('.countContext').on('keyup', function() {\r\n");
          out.write("	        $('.counts p em').html($(this).val().length);\r\n");
          out.write("	    });\r\n");
          out.write("	});\r\n");
          out.write("	\r\n");
          out.write("	/* 글자수 reset */\r\n");
          out.write("	function count_reset(){\r\n");
          out.write("		$('.countContext').val(\"\");\r\n");
          out.write("		$('.counts p em').html(\"0\");\r\n");
          out.write("	}\r\n");
          out.write("</script>\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("   .toolContent_countContent{ width : 1300px; margin : auto; }\r\n");
          out.write("   .countContext_left{ \r\n");
          out.write("       width : 750px; \r\n");
          out.write("       float : left;\r\n");
          out.write("    }\r\n");
          out.write("   .countContext{    \r\n");
          out.write("       width : 100%;\r\n");
          out.write("       height : 550px;\r\n");
          out.write("       resize : none; \r\n");
          out.write("       padding : 20px; \r\n");
          out.write("       box-sizing : border-box;\r\n");
          out.write("   }\r\n");
          out.write("   .countSu{ text-align : right; }\r\n");
          out.write("   .countContext_right{\r\n");
          out.write("       width : 400px;\r\n");
          out.write("       height : 550px;\r\n");
          out.write("       float : left;\r\n");
          out.write("       padding : 30px;\r\n");
          out.write("       background-color : #caccce;\r\n");
          out.write("       box-sizing : border-box;\r\n");
          out.write("   }\r\n");
          out.write("   .countContext_right h4{ font-weight : bold; margin-bottom:15px;}\r\n");
          out.write("   .counts{ \r\n");
          out.write("       width : 100%; \r\n");
          out.write("       background-color : white; \r\n");
          out.write("       padding : 5px; \r\n");
          out.write("       box-sizing : border-box;\r\n");
          out.write("   }\r\n");
          out.write("   .counts{ margin-bottom : 40px; }\r\n");
          out.write("   .counts > p {display : inline-block; width : 80%;}\r\n");
          out.write("   .counts > input {}\r\n");
          out.write("   .counts > p > em { color : red; }\r\n");
          out.write("   .countBottom{ clear : both; }\r\n");
          out.write("</style>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("   <!-- 공고 현황 -->\r\n");
          out.write("   <div class = \"toolContent toolContent_countContent\">\r\n");
          out.write("      <h2 class = \"toolTitle\">글자수 세기</h2>\r\n");
          out.write("	  <div class = \"toolBox\">\r\n");
          out.write("	      <div class = \"countContext_left\">\r\n");
          out.write("	         <textarea class = \"countContext\" name = \"countContext\" rows=\"25\" cols=\"10\" placeholder = \"자기소개서를 입력해주세요. 최소 200자는 적어주는 편이 좋습니다.\"></textarea>\r\n");
          out.write("	      	 <div class = \"countSu\"></div>\r\n");
          out.write("	      </div>\r\n");
          out.write("	      <div class = \"countContext_right\">\r\n");
          out.write("	          <div class = \"counts\">\r\n");
          out.write("	             <p>현재까지 글자 수 : <em>0</em></p>\r\n");
          out.write("	             <input type = \"button\" value = \"초기화\" onclick = \"count_reset();\">\r\n");
          out.write("	          </div>\r\n");
          out.write("	          <div>\r\n");
          out.write("	            <h4>TIP! 회사가 선호하는 자기소개 글자수</h4>\r\n");
          out.write("	            <strong>1. 글자수 자체는 큰 의미가 없다</strong>\r\n");
          out.write("	            <p>여백의 미가 생긴다면 성의 없어 보일까 걱정이 되겠지만 인사담당자들은 글자수 제한을 다 채울 필요는 없다고 강조한다.</p>\r\n");
          out.write("	            <strong>2. 보통 80~90% 정도를 채우면 적당하다.</strong>\r\n");
          out.write("	            <p>제한 글자수가 있다면 어느 정도 적정 분량을 채워야 성실성을 보여줄 수 있을 것. 80~90% 분량을 채우는 것은 최소한의 성의다. 핵심만 간단히!</p>\r\n");
          out.write("	            <strong>3. 한정된 글자수 내에서 진심과 열정을 보여라</strong>\r\n");
          out.write("	            <p>기업분석이 완벽하게 이루어져 있고 입사에 대한 진정성이 있다면 글자수 제한은 오히려 장벽이 될 것이다. 진심과 열정을 다해 자소서를 작성하는 것이 가장 현명한 방법이다.</p>\r\n");
          out.write("	            <p><a href = \"https://www.jobkorea.co.kr/goodjob/tip/view?News_No=11759\">[출처] 잡코리아</a></p>\r\n");
          out.write("	          </div>\r\n");
          out.write("	      </div>\r\n");
          out.write("	      <div class = \"countBottom\"></div>\r\n");
          out.write("      </div>\r\n");
          out.write("   </div>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write("\r\n");
          out.write("	         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
